name: CI/CD Pull Requests Close

on:
  pull_request:
    types: [closed]
  
jobs:
  # Inspect the information that is accessible in each context
  # https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log-file
  # You can delete this section
  jobinfo:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  preview_delete:
    runs-on: ubuntu-latest
    name: "Preview delete"
    steps:
      - name: Hello
        run: |
          echo "Hello World!"
            

  create_release:
    runs-on: "ubuntu-latest"
    if: github.event.pull_request.merged == true && startsWith( github.head_ref, 'release/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Get the version
        id: get_version
        run: |
          ref=$(echo "${{ github.head_ref }}")
          echo ::set-output name=VERSION::${ref/release\//}

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ github.token }}"
          automatic_release_tag: "v${{ steps.get_version.outputs.VERSION }}"
          prerelease: false
          title: "Release v${{ steps.get_version.outputs.VERSION }}"
          # files: |


  prod_deploy:
    needs: [ create_release ]
    runs-on: ubuntu-latest
    name: "Prod deploy"
    steps:
      - name: Hello
        run: |
          echo "Hello World!"